# create by pogg
# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # model depth multiple
width_multiple: 1.0  # layer channel multiple

# anchors
anchors:
  - [ 10,13, 16,30, 33,23 ]  # P3/8
  - [ 30,61, 62,45, 59,119 ]  # P4/16
  - [ 116,90, 156,198, 373,326 ]  # P5/32

# custom backbone
backbone:
  # [from, number, module, args]
  [ [ -1, 1, conv_bn_relu_maxpool, [ 32 ] ],    # 0-P2/4
    [ -1, 1, Shuffle_Block, [ 116, 2 ] ], # 1-P3/8
    [ -1, 3, Shuffle_Block, [ 116, 1 ] ], # 2
    [ -1, 1, Shuffle_Block, [ 232, 2 ] ], # 3-P4/16
    [ -1, 7, Shuffle_Block, [ 232, 1 ] ], # 4
    [ -1, 1, Shuffle_Block, [ 464, 2 ] ], # 5-P5/32
    [ -1, 3, Shuffle_Block, [ 464, 1 ] ], # 6
  ]

# YOLOv5 head
head:
  [ [ -1, 1, Conv, [ 128, 1, 1 ] ],
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 4 ], 1, Concat, [ 1 ] ],  # cat backbone P4
    [ -1, 1, C3, [ 128, False ] ],  # 10

    [ -1, 1, Conv, [ 64, 1, 1 ] ],
    [ -1, 1, nn.Upsample, [ None, 2, 'nearest' ] ],
    [ [ -1, 2 ], 1, Concat, [ 1 ] ],  # cat backbone P3
    [ -1, 1, C3, [ 64, False ] ],  # 14 (P3/8-small)

    [ -1, 1, Conv, [ 64, 3, 2 ] ],
    [ [ -1, 11 ], 1, Concat, [ 1 ] ],  # cat head P4
    [ -1, 1, C3, [ 128, False ] ],  # 17 (P4/16-medium)

    [ -1, 1, Conv, [ 128, 3, 2 ] ],
    [ [ -1, 7 ], 1, Concat, [ 1 ] ],  # cat head P5
    [ -1, 1, C3, [ 256, False ] ],  # 20 (P5/32-large)

    [ [ 14, 17, 20 ], 1, Detect, [ nc, anchors ] ],  # Detect(P3, P4, P5)
  ]
