aa: rand-m9-mstd1.0-inc1
amp: false
aug_splits: 0
batch_size: 128
bce_loss: false
bce_target_thresh: null
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 10
class_map: ''
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
cutmix: 1.0
cutmix_minmax: null
data_dir: gs://xxx-imagenet
dataset: tfds/imagenet2012:5.0.0
dataset_download: false
decay_epochs: 1.0
decay_rate: 0.988
dist_bn: reduce
drop: 0.3
drop_block: null
drop_connect: null
drop_path: 0.1
epoch_repeats: 0.0
epochs: 600
eval_metric: top1
experiment: ''
force_cpu: false
gp: null
hflip: 0.5
img_size: null
initial_checkpoint: ''
input_size: null
interpolation: ''
jsd: false
jsd_loss: false
local_rank: 0
log_interval: 50
log_wandb: false
lr: 0.1
lr_cycle_decay: 0.5
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_k_decay: 1.0
lr_noise:
- 0.45
- 1.0
lr_noise_pct: 0.45
lr_noise_std: 1.0
mean: null
min_lr: 5.0e-06
mixup: 0.2
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: xxx
model_ema: true
model_ema_decay: 0.99995
model_ema_force_cpu: false
momentum: 0.9
no_aug: false
no_resume_opt: false
num_classes: null
opt: rmsproptf
opt_betas: null
opt_eps: 0.001
output: ''
patience_epochs: 10
pin_mem: false
pretrained: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
reprob: 0.35
resplit: false
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: step
seed: 21
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_multi_epochs_loader: false
val_split: validation
validation_batch_size: 125
validation_batch_size_multiplier: 1
vflip: 0.0
warmup_epochs: 10
warmup_lr: 1.0e-06
weight_decay: 7.0e-06
workers: 4