data_root: /neutrino/datasets/vww
model: mobilenetv2_wd4
dataset: vww
pretraining_dataset: imagenet
epochs: 200
batch_size: 64
test_batch_size: 256
imgsz: 224
nosave: false
device: ''
workers: 8
project: /home/ravish/ravish/mobilenetv1_025_zoo_commit/deeplite-torch-zoo/training_scripts/classification/ultralytics/runs/train-cls
name: exp
exist_ok: false
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
verbose: false
seed: 0
local_rank: -1
kd_model_name: null
kd_model_checkpoint: null
alpha_kd: 5
use_kd_only_loss: false
save_dir: /home/ravish/ravish/mobilenetv1_025_zoo_commit/deeplite-torch-zoo/training_scripts/classification/ultralytics/runs/train-cls/exp3
