# https://github.com/LSH9832/edgeyolo

# parameters
nc: 80  # number of classes
depth_multiple: 1.0  # models depth multiple
width_multiple: 1.0  # layer channel multiple
activation_type: silu

anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32

# edgeyolo backbone
backbone:
  # [from, number, module, args]
  [[-1, 1, RepConv, [32, 3, 1]],  # 0

   [-1, 1, RepConv, [64, 3, 2]],  # 1-P1/2
   [-1, 1, RepConv, [64, 3, 1]],

   [-1, 1, RepConv, [96, 3, 2]],  # 3-P2/4
   [-1, 1, Conv, [48, 1, 1]],
   [-2, 1, Conv, [48, 1, 1]],
   [-1, 1, RepConv, [48, 3, 1]],
   [-1, 1, RepConv, [48, 3, 1]],
   [-1, 1, RepConv, [48, 3, 1]],
   [-1, 1, RepConv, [48, 3, 1]],
   [[-1, -2], 1, Shortcut, [1]],
   [[-4, -5], 1, Shortcut, [1]],
   [[-1, -2, -7, -8], 1, Concat, [1]],
   [-1, 1, Conv, [160, 1, 1]],  # 13

   [-1, 1, MP, []],
   [-1, 1, Conv, [96, 1, 1]],
   [-3, 1, Conv, [96, 1, 1]],
   [-1, 1, RepConv, [96, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 18-P3/8
   [-1, 1, Conv, [96, 1, 1]],
   [-2, 1, Conv, [96, 1, 1]],
   [-1, 1, RepConv, [96, 3, 1]],
   [-1, 1, RepConv, [96, 3, 1]],
   [-1, 1, RepConv, [96, 3, 1]],
   [-1, 1, RepConv, [96, 3, 1]],
   [[-1, -2], 1, Shortcut, [1]],
   [[-4, -5], 1, Shortcut, [1]],
   [[-1, -2, -7, -8], 1, Concat, [1]],
   [-1, 1, Conv, [320, 1, 1]],  # 28

   [-1, 1, MP, []],
   [-1, 1, Conv, [192, 1, 1]],
   [-3, 1, Conv, [192, 1, 1]],
   [-1, 1, RepConv, [192, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 33-P4/16
   [-1, 1, Conv, [192, 1, 1]],
   [-2, 1, Conv, [192, 1, 1]],
   [-1, 1, RepConv, [192, 3, 1]],
   [-1, 1, RepConv, [192, 3, 1]],
   [-1, 1, RepConv, [192, 3, 1]],
   [-1, 1, RepConv, [192, 3, 1]],
   [[-1, -2], 1, Shortcut, [1]],
   [[-4, -5], 1, Shortcut, [1]],
   [[-1, -2, -7, -8], 1, Concat, [1]],
   [-1, 1, Conv, [640, 1, 1]],  # 43

   [-1, 1, MP, []],
   [-1, 1, Conv, [384, 1, 1]],
   [-3, 1, Conv, [384, 1, 1]],
   [-1, 1, RepConv, [384, 3, 2]],
   [[-1, -3], 1, Concat, [1]],  # 48-P5/32
   [-1, 1, Conv, [192, 1, 1]],
   [-2, 1, Conv, [192, 1, 1]],
   [-1, 1, RepConv, [192, 3, 1]],
   [-1, 1, RepConv, [192, 3, 1]],
   [-1, 1, RepConv, [192, 3, 1]],
   [-1, 1, Conv, [192, 3, 1]],
   [[-1, -2], 1, Shortcut, [1]],
   [[-4, -5], 1, Shortcut, [1]],
   [[-1, -2, -7, -8], 1, Concat, [1]],
   [-1, 1, Conv, [640, 1, 1]],  # 58
  ]

# edgeyolo head
head:
  [[-1, 1, SPPCSPC, [320]], # 59

   [-1, 1, Conv, [160, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [43, 1, Conv, [160, 1, 1]], # route backbone P4
   [[-1, -2], 1, Concat, [1]],

   [-1, 1, Conv, [160, 1, 1]],
   [-2, 1, Conv, [160, 1, 1]],
   [-1, 1, RepConv, [80, 3, 1]],
   [-1, 1, RepConv, [80, 3, 1]],
   [-1, 1, RepConv, [80, 3, 1]],
   [-1, 1, RepConv, [80, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [160, 1, 1]], # 71

   [-1, 1, Conv, [80, 1, 1]],
   [-1, 1, nn.Upsample, [None, 2, 'nearest']],
   [28, 1, Conv, [80, 1, 1]], # route backbone P3
   [[-1, -2], 1, Concat, [1]],

   [-1, 1, Conv, [80, 1, 1]],
   [-2, 1, Conv, [80, 1, 1]],
   [-1, 1, RepConv, [40, 3, 1]],
   [-1, 1, RepConv, [40, 3, 1]],
   [-1, 1, RepConv, [40, 3, 1]],
   [-1, 1, RepConv, [40, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [80, 1, 1]], # 83

   [-1, 1, MP, []],
   [-1, 1, Conv, [80, 1, 1]],
   [-3, 1, Conv, [80, 1, 1]],
   [-1, 1, RepConv, [80, 3, 2]],
   [[-1, -3, 71], 1, Concat, [1]],

   [-1, 1, Conv, [160, 1, 1]],
   [-2, 1, Conv, [160, 1, 1]],
   [-1, 1, RepConv, [80, 3, 1]],
   [-1, 1, RepConv, [80, 3, 1]],
   [-1, 1, RepConv, [80, 3, 1]],
   [-1, 1, RepConv, [80, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [160, 1, 1]], # 96

   [-1, 1, MP, []],
   [-1, 1, Conv, [160, 1, 1]],
   [-3, 1, Conv, [160, 1, 1]],
   [-1, 1, RepConv, [160, 3, 2]],
   [[-1, -3, 59], 1, Concat, [1]],

   [-1, 1, Conv, [320, 1, 1]],
   [-2, 1, Conv, [320, 1, 1]],
   [-1, 1, RepConv, [160, 3, 1]],
   [-1, 1, RepConv, [160, 3, 1]],
   [-1, 1, RepConv, [160, 3, 1]],
   [-1, 1, RepConv, [160, 3, 1]],
   [[-1, -2, -3, -4, -5, -6], 1, Concat, [1]],
   [-1, 1, Conv, [320, 1, 1]], # 109

   [83, 1, RepConv, [160, 3, 1]],   # 110
   [96, 1, RepConv, [320, 3, 1]],   # 111
   [109, 1, RepConv, [640, 3, 1]], # 112

   [[110,111,112], 1, Detect, [nc, anchors]],
  ]