backbone:
  type: yolo8
  version: s
neck:
  v8FPN:
    channel_outs: [512, 256, 256]
    version: s
  v8PAN:
    channel_outs: [256, 512, 512, 1024]
    version: s
head:
  nc: 1
  anchors:
    - [10,13, 16,30, 33,23]  # P3/8
    - [30,61, 62,45, 59,119]  # P4/16
    - [116,90, 156,198, 373,326]  # P5/32
